### ISSUE TITLE
CoNLL-2003 data

### ISSUE THREAD

**Issue by malagus** [raymondhs/pytorch-char-rnn-truecase#1]
Hi. I'm working in my master thesis on using neutral networks for text capitalization. I was wondering if you use any additional data clearing methods (  for example remove sentences where all data is capitalized ) or use data as is ?

**Comment by raymondhs** [comment]
Hello, sorry for the late reply. Yes, news headlines, which are all in upper case words, are discarded (it's also mentioned in Footnote 1 of the paper).

**Comment by malagus** [comment]
Thanks for information. Somehow  I'm miss that footnote.
